# Generated by Django 5.2 on 2025-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="hires_made",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employer",
            name="company_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="employer",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="employer",
            name="mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
