# Generated by Django 5.2 on 2025-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_agentmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmessage",
            name="agent_type",
            field=models.CharField(
                choices=[("intern", "Intern"), ("employer", "Employer")],
                default="intern",
                max_length=20,
            ),
        ),
    ]
