# Generated by Django 5.2 on 2025-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_agentmessage_agent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmessage",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("intern", "Intern"),
                    ("employer", "Employer"),
                    ("application", "Application"),
                ],
                default="intern",
                max_length=20,
            ),
        ),
    ]
