"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path

from decouple import config

# ───────────────────────────────────────────────────────────────
# Core paths
# ───────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ───────────────────────────────────────────────────────────────
# Security
# ───────────────────────────────────────────────────────────────
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-t3)d^wlmu#t*y0l^igykpzt6ri!ba_*=oia$as61g$j9ft0#m@",
)
DEBUG = config("DEBUG", default=True, cast=bool)
ALLOWED_HOSTS: list[str] = []

# ───────────────────────────────────────────────────────────────
# Applications
# ───────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    # Third-party first so their migrations run early ↓
    "corsheaders",  # ← NEW
    "drf_spectacular",
    "rest_framework",
    "rest_framework_simplejwt",
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "accounts",
    "internships",
    "profiles",
    "voice",
]

# ───────────────────────────────────────────────────────────────
# Middleware
# ───────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ← NEW (must be first)
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ───────────────────────────────────────────────────────────────
# URLs / WSGI
# ───────────────────────────────────────────────────────────────
ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"

# ───────────────────────────────────────────────────────────────
# Templates
# ───────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ───────────────────────────────────────────────────────────────
# Database (SQLite for dev; override with DATABASE_URL in env)
# ───────────────────────────────────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ───────────────────────────────────────────────────────────────
# Password validation
# ───────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ───────────────────────────────────────────────────────────────
# REST framework
# ───────────────────────────────────────────────────────────────
AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ───────────────────────────────────────────────────────────────
# CORS  (dev-only – loosen as needed for prod)
# ───────────────────────────────────────────────────────────────
CORS_ALLOW_ALL_ORIGINS = True  # allow http://localhost:* etc.
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [  # include Auth & JSON headers
    "authorization",
    "content-type",
    "accept",
    "origin",
    "user-agent",
    "x-requested-with",
]

# ───────────────────────────────────────────────────────────────
# Internationalisation / static
# ───────────────────────────────────────────────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

APPEND_SLASH = False
