# Generated by Django 5.2 on 2025-06-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0002_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="references",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="internship",
            name="external_application_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="requires_cover_letter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internship",
            name="requires_references",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internship",
            name="requires_resume",
            field=models.BooleanField(default=False),
        ),
    ]
