# Generated by Django 5.2 on 2025-06-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "internships",
            "0003_application_cover_letter_application_references_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="references",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
