name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: market
          POSTGRES_PASSWORD: market
          POSTGRES_DB: market_test
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U market"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest
      - name: Run ruff / black
        run: |
          pip install ruff black
          ruff backend/ internships/
          black --check backend/ internships/

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm --prefix frontend ci
      - name: Type check & lint
        run: |
          npx --prefix frontend next lint
          npx --prefix frontend tsc --noEmit
